name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 */4 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          config_timezone: Europe/Berlin
          plugin_languages: yes
          plugin_languages_indepth: true
          plugin_languages_details: percentage, lines
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_sections: base
#          plugin_habits: yes #Somehow this fucks up the svg
          token: ${{ secrets.METRICS_TOKEN }}
